### PR TITLE
sockets.rs update to match new RL

### PR DESCRIPTION
**Pull request by Tenshi147**
Mojang API was updated and rate limit was dropped from 6/gc to 2

### CODE REVIEW

**Comment by Tenshi147** [comment]
Turns out they updated again, this is now 5 per IP

**Comment by Tenshi147** [comment]
Actually lets leave this open or you might not see it :)

**Comment by tropicbliss** [comment]
Given that Mojang keeps changing its rate limit I'll say it's more convenient to leave it as it is for now and see if their rate limit stabilises. I'll leave this pull request open for now :)

**Comment by Tenshi147** [comment]
Alrighty

**Pull request merged**
